version: '3.7'

volumes:
    prometheus_data: {}

networks:
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager

    networks:
      - back-tier
    restart: always

  snmp-exporter:
    image: prom/snmp-exporter:latest
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    ports:
      - 9116:9116
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox_exporter/:/etc/blackbox_exporter/
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    ports:
      - 9115:9115
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    