version: '3.7'

volumes:
    prometheus_data: {}
    statping_data: {}

networks:
  back-tier:

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager

    networks:
      - back-tier
    restart: always

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    ports:
      - 9116:9116
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    volumes:
      - ./blackbox_exporter/:/etc/blackbox_exporter/
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    ports:
      - 9115:9115
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    
  statping:
    image: statping/statping
    container_name: statping
    restart: always
    ports:
      - 8080:8080
    volumes:
      - statping_data:/app
# links:
#   - postgres
    environment:
      DB_CONN: sqlite
#     DB_CONN: postgres
#     DB_HOST: postgres
#     DB_PORT: 5432
#     DB_DATABASE: statping
#     DB_USER: root
#     DB_PASS: password123

# postgres:
#   container_name: postgres
#   image: postgres:10.0-alpine
#   ports:
#     - 5432:5432
#   volumes:
#     - pg_data:/var/lib/postgresql/data/pg_data
#   environment:
#     POSTGRES_PASSWORD: password123
#     POSTGRES_DB: statping
#     POSTGRES_USER: root
#     POSTGRES_PORT: 5432
#     PGDATA: /var/lib/postgresql/data/pg_data
